### ISSUE TITLE
Spy's chances of getting away are not less than one in a million

### ISSUE THREAD

**Issue by TofuLynx** [oreilly-qc/oreilly-qc.github.io#12]
# Context
In Chapter 2: One Qubit, a paragraph of Quantum Spy Hunter was corrected, as mentioned in the [errata](https://github.com/oreilly-qc/oreilly-qc.github.io/blob/master/errata/errata.md):

> "Any spy who tries to read one of these qubits has a 12.5% chance of getting caught. So even if Alice and Bob only use 50 of them in the whole transfer, the spy’s chances of getting away are far less than one in a million."

# Issue
However, with the correct probability, the spy's chances of getting away aren't far less than one in a million anymore. When it was 25%, the probability of getting away with 50 "spy hunter" qubits was ~5,66e-7, which is less than one in a million (~0,566 in a million), as stated. With the correct value 12,5%, the probability of getting away with 50 "spy hunter" qubits is ~1,26e-3, which is actually around 1260 in a million.

# Suggestion
I suggest one of three possible paragraphs that solve the issue:

1. "Any spy who tries to read one of these qubits has a 12.5% chance of getting caught. So even if Alice and Bob only use 105 of them in the whole transfer, the spy’s chances of getting away are far less than one in a million." _(changed «50» to «105»)_

2. "Any spy who tries to read one of these qubits has a 12.5% chance of getting caught. So even if Alice and Bob only use 100 of them in the whole transfer, the spy’s chances of getting away are close to one in a million." _(changed «50» to «100» and «getting away are far less than one in a million» to «getting away are close to one in a million»)_

3. "Any spy who tries to read one of these qubits has a 12.5% chance of getting caught. So even if Alice and Bob only use 50 of them in the whole transfer, the spy’s chances of getting away are very low."  _(changed «getting away are far less than one in a million» to «getting away are very low»)_

Personally, I am a fan of the second paragraph. I hope I have been clear enough!

**Comment by machinelevel** [comment]
Thanks very much! You're of course correct, and the errata sheet is updated in 0336c61
