### ISSUE TITLE
Missing value in Figure 7-6

### ISSUE THREAD

**Issue by TofuLynx** [oreilly-qc/oreilly-qc.github.io#15]
# Context and Issue
Although I am probably being nitpicky, I am not sure this was intentional. Figure 7-6 in Chapter 7: QFT: Quantum Fourier Transform, the value |15> is missing. Since this is a 4 qubit system, it should display 16 values, from |0> to |15>, unless stated otherwise. The missing value is important to have a good idea about the different visual patterns of the signals' values.

# Suggestion
As aforementioned, if this value was not intentionally removed, I suggest adding the missing value to the figure, displaying all the 16 values.

**Comment by machinelevel** [comment]
Thank you! You're exactly correct, the final column is missing. Added (along with a corrected image in case you need it) to the [errata page](https://github.com/oreilly-qc/oreilly-qc.github.io/blob/master/errata/errata.md), in commit 370c5ce0c39ce9221abdf1a81923878569de303c
