### ISSUE TITLE
Figure 3-2 Appears to be Inaccurate

### ISSUE THREAD

**Issue by simplygreatwork** [oreilly-qc/oreilly-qc.github.io#26]
For the top part of the figure to be produced, qubits 1 and 3 would need to be swapped. As is, the 3 qubit arrangement would produce 0 0 0 0 .25 .25 .25 .25. I could be wrong because I just bought your book a day ago. ;-)

Love this book! Before buying this book I had difficulty understanding magnitude effects of modifying phase. The root not example gave me hope. I'm only a couple of chapters in. Excellent work folks!

**Comment by simplygreatwork** [comment]
After more investigation with QCEngine and quantum-circuit, I am closing this issue. I had been using a different library which was returning results with a different ordering.

**Comment by machinelevel** [comment]
Hi Philip!
I just wanted to drop you a note and say thank you. I appreciate your very kind comments about the book, and also your willingness to point out problems when you see them. This one looks okay (as you mention) however a few others have definitely been spotted, and this helps us, as well as other readers.

We've collected most of the spotted errata [**here**](https://github.com/oreilly-qc/oreilly-qc.github.io/blob/master/errata/errata.md) in case that's useful.

Thank you again, and please feel free to reach out anytime!
Cheers,
`- ej` a.k.a. octopus@machinelevel.com
