### ISSUE TITLE
[TABLE 2-2] 0.95|0> + 0.35|1>  is strange

### ISSUE THREAD

**Issue by jongidal** [oreilly-qc/oreilly-qc.github.io#27]
I think the forth row is wrong 0.95^2 + 0.35^2 != 1.  It should be 0.95|0> + 0.31|1>.

**Comment by machinelevel** [comment]
Thanks for pointing this out! It's been added to the [Errata page](https://github.com/oreilly-qc/oreilly-qc.github.io/blob/master/errata/errata.md).
