### ISSUE TITLE
Example 2-3 phase should be -90 instead of 90

### ISSUE THREAD

**Issue by checky2010** [oreilly-qc/oreilly-qc.github.io#28]
I think that in example 2-3 (in the book), the phase should be -90, like in the simulator, instead of 90. 

And therefore, Figure 2-16 and 2-18 are wrong as well.

**Comment by machinelevel** [comment]
Hi Jonas, you're right, and thanks for pointing this out. I've updated the [Errata page](https://github.com/oreilly-qc/oreilly-qc.github.io/blob/master/errata/errata.md).

Jim Blinn famously advised "Always make sure you have an even number of sign errors". Accomplished, there are 2. :]
