### ISSUE TITLE
Page 133, Figures 7-9 through 7-11

### ISSUE THREAD

**Issue by joshuaguerin** [oreilly-qc/oreilly-qc.github.io#47]
Perhaps I am going crazy and someone could help point me in the right direction.

Figures 7-9 and 7-10 appear to include the same sampled wave. The resulting diagram in 7-10 shows the output at 8 Hz, and the book makes explicit reference to completion of eight full oscillations, but I am counting 6 peaks in both figures on page 133.

Am I misreading this somehow? It would seem to me that the upper-right portion of Figure 7-11 would correspond to 8 Hz (I am counting 8 peaks in that image).

**Comment by machinelevel** [comment]
Hi Dr. Guerin! Thanks for spotting this. You're correct, it looks like the text and labels were written for the 8Hz sample in Figure 7-11, and not for the 6Hz wave in 7-10. This has been added to the errata page [**here**](https://github.com/oreilly-qc/oreilly-qc.github.io/blob/master/errata/errata.md#figure-7-10-and-surrounding-text) with thanks to you. Please let me know if that looks ok to you. I'll close this, but we can re-open as needed.

Cheers and thank you, - ej
