### ISSUE TITLE
Documentation: bits in wrong order

### ISSUE THREAD

**Issue by rgobbel** [oreilly-qc/oreilly-qc.github.io#49]
The "Working with qubits" cheatsheet says "For example, `0x4`, `0b001` and `4` would all specify the third of three qubits ...". The binary value for 4 should be `0b100`. The error is repeated in the next sentence: the three ways to select the second two of the three qubits in the example should be `0x2|0x4`, `0b010|0b100`, and `6`, not `0x2|0x4`, `0b010|0b001`, and `3`.

**Comment by machinelevel** [comment]
Thanks for spotting this! Indeed, the `0b` forms of these binary numbers are incorrect. Fixed in commits ade464819dc08d56630a597fe20f9b1bcab4883c and c4f99585d0778a757b9ef21230b59b9f5093bbb4!

**Comment by machinelevel** [comment]
(I've closed this, but if you don't see the fixed version please feel free to re-open)
